---
title: "Test proyect csgo"
author: ""
date: "2023-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(psych)
library(caret)
library(e1071)
```

```{r}
df <- read.csv("csgo_round_snapshots.csv")
```


```{r}
df_test <- head(df, 500)
```


```{r}
dim(df_test)
```

```{r}
colnames(df_test)
```

```{r}
head(df_test)
```

```{r}
summary(df_test)
```

```{r}
str(df_test)
```



```{r}
any(duplicated(df_test))
```


```{r}
df_test[duplicated(df_test), ]
```

```{r}
df_test <- unique(df_test)
dim(df_test)
```


```{r}
str(df_test)
```


```{r}
View(df_test)
```

```{r}
library(stringr)

df_test$map <- sub("de_","", df_test$map)

df_test$map <- str_to_title(df_test$map)

```

```{r}
View(df_test)
```

```{r}
dim(df_test)
```

```{r}
colSums(is.na(df_test))

```

```{r}
which(colSums(df_test == 0) == nrow(df_test))
```

```{r}
df_test <- df_test[, colSums(df_test != 0) > 0]
```

```{r}
dim(df_test)
```

```{r}
head(df_test)
```

# Label encoding all categorical values
https://www.kaggle.com/code/abj2000/csgo-round-winner-prediction-88-accuracy?scriptVersionId=63107599&cellId=17

# Normalizing the data using Standard Scalar
https://www.kaggle.com/code/abj2000/csgo-round-winner-prediction-88-accuracy?scriptVersionId=63107599&cellId=25

# Splitting the data into X and Y
https://www.kaggle.com/code/abj2000/csgo-round-winner-prediction-88-accuracy?scriptVersionId=63107599&cellId=33

# Train Test Split
https://www.kaggle.com/code/abj2000/csgo-round-winner-prediction-88-accuracy?scriptVersionId=63107599&cellId=38

# Training and Evaluation
https://www.kaggle.com/code/abj2000/csgo-round-winner-prediction-88-accuracy?scriptVersionId=63107599&cellId=40







